import AOSProvider from "@/components/aos/AOSProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HyunJinNo's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSProvider>
          {/* <Header /> */}
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
